In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [52]:
data = pd.read_csv('egypt1975.csv', sep = ';')

# Columns
1. maximum air temperature (°C)
2. minimum air temperature (°C)
3. mean air temperature (°C)
4. mean daily wind speed at 10m (m/s)
5. vapour pressure (hPa)
6. sum of precipitation (mm/day)
7. potential evaporation from a free water surface (mm/day)
8. potential evapotranspiration from a crop canopy (mm/day)
9. potential evaporation from a moist bare soil surface (mm/day)
10. total global radiation (KJ/m2/day)
11. Snow Depth

In [88]:
data.head()

,GRID_NO,LATITUDE,LONGITUDE,ALTITUDE,DAY,TEMPERATURE_MAX,TEMPERATURE_MIN,TEMPERATURE_AVG,WINDSPEED,VAPOURPRESSURE,PRECIPITATION,E0,ES0,ET0,RADIATION
0,28193,31.53312,31.90678,5,19800101,20.0,6.0,13.0,4.2,8.37,3.0,2.39,1.95,3.02,18103
1,28193,31.53312,31.90678,5,19800102,15.0,8.0,11.5,3.5,10.80,0.0,1.55,1.23,1.61,14007
2,28193,31.53312,31.90678,5,19800103,18.5,6.0,12.3,2.4,9.10,0.0,1.99,1.67,2.23,12872
3,28193,31.53312,31.90678,5,19800104,18.0,9.0,13.5,7.9,9.21,0.0,3.22,2.84,3.44,15414
4,28193,31.53312,31.90678,5,19800105,14.0,10.0,12.0,10.6,9.65,2.5,2.95,2.67,2.68,11644

In [54]:
lat = data.LATITUDE.unique()
long = data.LONGITUDE.unique()

In [55]:
locations = list(zip(lat,long))

In [56]:
locations

[(31.53312, 31.906779999999998),
 (28.82912, 29.981679999999997),
 (28.87405, 30.774420000000003),
 (31.07981, 31.338520000000003),
 (31.361290000000004, 31.144609999999997),
 (30.98198, 30.77614),
 (31.141379999999998, 31.086159999999996),
 (27.33403, 32.209140000000005),
 (26.937720000000002, 33.655640000000005),
 (27.618709999999997, 32.0224),
 (27.425109999999997, 32.74921),
 (27.29263, 33.23239),
 (27.22537, 33.47357),
 (27.15665, 33.71103),
 (28.027509999999996, 31.34733),
 (27.32071, 33.70263),
 (28.1866, 31.64635),
 (27.86553, 32.864259999999994),
 (27.933940000000003, 33.392559999999996),
 (29.00556, 32.11782),
 (29.16113, 32.42238),
 (28.216559999999998, 28.55177),
 (28.052540000000004, 29.28773),
 (28.83186, 28.943379999999998),
 (28.99932, 29.24046),
 (29.28936, 31.928990000000002),
 (29.57268, 31.739240000000002),
 (29.917559999999998, 31.29972),
 (29.729329999999997, 32.04535),
 (30.26019, 30.85722),
 (30.19939, 31.10722),
 (28.046129999999998, 28.259209999999996),
 (27.884690000000003, 28.994220000000002),
 (28.670690000000004, 26.33134),
 (28.4759, 27.32045),
 (28.425440000000002, 27.56717),
 (29.348940000000002, 25.16951),
 (29.072129999999998, 26.66552),
 (29.14798, 27.456159999999997),
 (29.754540000000002, 25.50135),
 (29.520659999999996, 26.753559999999997),
 (30.068109999999997, 25.039189999999998),
 (29.79308, 26.54754),
 (29.74472, 26.798140000000004),
 (29.59533, 27.54855),
 (29.5441, 27.7982),
 (30.20397, 25.58472),
 (29.91941, 27.094079999999998),
 (29.6625, 28.34536),
 (30.517840000000003, 25.120739999999998),
 (30.38273, 25.8797),
 (30.74251, 25.16204),
 (30.51298, 26.42902),
 (30.87715, 25.71247),
 (31.055090000000003, 26.010460000000002),
 (31.23187, 26.309890000000003),
 (30.88185, 28.08857),
 (31.67473, 25.04215),
 (31.48753, 26.09468),
 (31.00627, 28.38888),
 (30.951009999999997, 28.62991),
 (30.812240000000003, 29.41587),
 (30.97865, 29.724890000000002),
 (28.39831, 26.5362),
 (28.251590000000004, 27.27597),
 (30.761570000000003, 30.71926),
 (30.2956, 31.664590000000004),
 (29.49162, 34.64032),
 (30.1917, 32.971540000000005),
 (30.27552, 33.53184),
 (29.997429999999998, 34.52435),
 (30.4249, 33.84476),
 (30.711470000000002, 33.65985),
 (31.09475, 33.00155),
 (30.860090000000003, 33.97495),
 (30.79028, 34.224909999999994),
 (30.936659999999996, 34.54155),
 (31.224290000000003, 34.35844),
 (28.781470000000002, 33.22203),
 (28.975009999999997, 33.21212),
 (28.90868, 34.20265),
 (28.78732, 34.59758),
 (29.126790000000003, 34.26594),
 (29.4839, 33.837379999999996),
 (29.274079999999998, 34.57546),
 (30.82638, 32.34485),
 (28.326929999999997, 30.12401),
 (31.299529999999997, 31.39757),
 (28.592370000000003, 30.9663),
 (28.81363, 31.02073),
 (30.85994, 31.279970000000002),
 (31.07909, 32.1623),
 (31.19102, 32.39393),
 (27.4236, 30.943609999999996),
 (27.52297, 31.482259999999997),
 (27.39769, 31.967109999999998),
 (27.005470000000003, 33.415240000000004),
 (26.868709999999997, 33.869609999999994),
 (27.80612, 31.29317),
 (27.68187, 31.779590000000002),
 (28.149359999999998, 30.858790000000003),
 (27.96555, 31.5912),
 (27.64541, 32.8065),
 (28.344459999999998, 31.946620000000003),
 (28.6907, 31.512529999999998),
 (28.37122, 32.737140000000004),
 (28.469659999999998, 32.96062),
 (28.66321, 28.6476),
 (28.55392, 29.140729999999998),
 (28.72083, 29.43715),
 (29.1656, 29.53885),
 (29.387759999999997, 29.59034),
 (29.330679999999997, 29.838559999999998),
 (29.2729, 30.086509999999997),
 (29.7742, 29.944000000000003),
 (29.635240000000003, 31.491259999999997),
 (29.978890000000003, 31.0506),
 (28.09855, 28.013740000000002),
 (29.12364, 25.12965),
 (28.9241, 27.41054),
 (29.66092, 24.70811),
 (29.26887, 28.000040000000002),
 (29.97932, 25.54286),
 (30.428490000000004, 25.62694),
 (30.192429999999998, 26.888440000000003),
 (30.366540000000004, 27.18638),
 (30.10805, 28.44373),
 (30.330609999999997, 28.493540000000003),
 (31.278740000000003, 24.73474),
 (31.19149, 25.24571),
 (30.55302, 28.543770000000002),
 (30.274890000000003, 29.800659999999997),
 (31.11494, 27.85073),
 (28.672629999999998, 25.050929999999997),
 (28.3012, 27.0296),
 (30.232470000000003, 31.914279999999998),
 (30.45208, 31.9736),
 (30.67152, 32.03342),
 (29.632609999999996, 34.147529999999996),
 (30.54235, 32.53416),
 (30.4767, 32.78406),
 (30.9139, 32.90868),
 (30.84713, 33.1594),
 (30.572979999999998, 34.15898),
 (30.502679999999998, 34.40804),
 (31.018729999999998, 33.22113),
 (30.992040000000003, 33.47732),
 (30.719759999999997, 34.47452),
 (31.20771, 33.28483),
 (31.15075, 30.025309999999998),
 (28.32222, 33.77243),
 (29.104879999999998, 33.05993),
 (29.2256, 32.17583),
 (30.607290000000003, 32.28395),
 (31.236859999999997, 31.6497),
 (31.15617, 31.89647),
 (28.770979999999998, 30.22823),
 (28.71214, 30.474520000000002),
 (28.99278, 30.280990000000003),
 (29.255679999999998, 31.130940000000002),
 (30.57801, 31.47277),
 (30.79785, 31.53142),
 (31.04192, 30.523770000000003),
 (27.77357, 29.48303),
 (27.13894, 32.933609999999994),
 (27.054000000000002, 33.864959999999996),
 (27.93112, 32.62124),
 (28.151259999999997, 32.67895),
 (28.30282, 32.97695),
 (28.242490000000004, 33.60264),
 (28.785359999999997, 32.06028),
 (28.72127, 32.30574),
 (28.94128, 32.363820000000004),
 (26.984009999999998, 32.63602),
 (26.918490000000002, 32.876740000000005),
 (26.85228, 33.1172),
 (28.322409999999998, 28.059929999999998),
 (28.59814, 27.859679999999997),
 (28.330990000000003, 29.091490000000004),
 (28.7168, 28.40066),
 (28.60892, 28.89429),
 (29.05465, 28.99288),
 (29.494559999999996, 30.13958),
 (29.35243, 31.681859999999997),
 (29.81867, 30.7456),
 (29.50943, 31.986929999999997),
 (29.855520000000002, 31.54856),
 (30.320290000000004, 30.60693),
 (27.9392, 28.74945),
 (28.8982, 25.090120000000002),
 (28.80933, 25.587229999999998),
 (28.574709999999996, 26.82633),
 (28.98886, 25.87681),
 (28.79917, 26.87003),
 (29.392570000000003, 24.91943),
 (29.21375, 25.91848),
 (29.12005, 26.416729999999998),
 (29.0235, 26.91409),
 (28.97415, 27.16243),
 (29.48443, 25.71046),
 (29.296459999999996, 26.709359999999997),
 (29.198190000000004, 27.207459999999998),
 (29.663140000000002, 26.0029),
 (29.37173, 27.502159999999996),
 (29.109270000000002, 28.745040000000003),
 (29.88764, 26.04565),
 (29.43951, 28.29678),
 (30.29304, 25.07979),
 (30.143040000000003, 27.140040000000003),
 (29.885340000000003, 28.394340000000003),
 (30.652890000000003, 25.669520000000002),
 (30.60698, 25.92292),
 (30.416079999999997, 26.93417),
 (29.99962, 28.944879999999998),
 (30.73681, 26.47387),
 (31.23548, 24.99034),
 (31.03623, 27.3278),
 (30.828940000000003, 28.34163),
 (30.720940000000002, 28.84696),
 (31.038290000000003, 28.132009999999998),
 (30.801040000000004, 29.166840000000004),
 (28.538659999999997, 25.7945),
 (28.350109999999997, 26.783009999999997),
 (29.92006, 33.96444),
 (30.41035, 33.033640000000005),
 (30.959590000000002, 32.65747),
 (30.43168, 34.65676),
 (31.1113, 33.545609999999996),
 (31.0074, 34.29138),
 (31.23222, 34.16),
 (31.12585, 29.8359),
 (30.43835, 30.105490000000003),
 (30.541009999999996, 30.66286),
 (30.48072, 30.91374),
 (28.541059999999998, 33.83368),
 (28.40353, 34.319559999999996),
 (28.43923, 34.46567),
 (28.6904, 34.13988),
 (29.266820000000003, 32.99483),
 (28.838459999999998, 34.447309999999995),
 (29.445459999999997, 32.234320000000004),
 (30.3233, 32.4732),
 (28.20925, 30.61412),
 (28.490370000000002, 30.421640000000004),
 (29.09533, 30.828740000000003),
 (31.036340000000003, 32.40337),
 (31.28224, 32.21985),
 (27.70572, 30.75303),
 (27.71697, 29.727079999999997),
 (27.46067, 31.72482),
 (28.310190000000002, 31.15727),
 (28.24874, 31.401940000000003),
 (28.123759999999997, 31.89048),
 (27.99602, 32.37793),
 (27.79925, 33.107009999999995),
 (27.845959999999998, 33.555209999999995),
 (28.911440000000002, 31.568509999999996),
 (29.106540000000003, 32.592940000000006),
 (27.239309999999996, 31.67049),
 (27.11303, 32.15378),
 (29.2218, 29.29095),
 (29.444129999999998, 29.341859999999997),
 (29.55252, 29.891059999999996),
 (29.59768, 30.690479999999997),
 (29.8784, 30.496470000000002),
 (30.099420000000002, 30.551470000000002),
 (30.039509999999996, 30.80118),
 (29.79277, 31.7971),
 (30.13787, 31.35693),
 (28.62305, 26.578940000000003),
 (29.079420000000002, 25.37891),
 (29.0345, 25.62796),
 (28.649459999999998, 27.612609999999997),
 (29.259529999999998, 25.66904),
 (28.87333, 27.65843),
 (29.57412, 25.2097),
 (29.52964, 25.46019),
 (28.94006, 28.44861),
 (29.7092, 25.752229999999997),
 (29.32065, 27.75122),
 (29.645840000000003, 27.29865),
 (29.49216, 28.047620000000002),
 (30.112009999999998, 26.08876),
 (29.96864, 26.8431),
 (29.72213, 29.14388),
 (30.78623, 24.907970000000002),
 (30.560340000000004, 26.17608),
 (30.464890000000004, 26.68171),
 (30.265309999999996, 27.69008),
 (30.161179999999998, 28.19277),
 (30.48835, 27.738059999999997),
 (30.383909999999997, 28.241970000000002),
 (30.11022, 29.49718),
 (30.862990000000003, 27.026790000000002),
 (30.659240000000004, 28.03915),
 (30.498829999999998, 28.795690000000004),
 (31.405620000000003, 25.28845),
 (31.37091, 25.54389),
 (31.23268, 27.34399),
 (28.492590000000003, 26.04194),
 (30.075640000000003, 31.606340000000003),
 (30.35802, 31.414609999999996),
 (30.5154, 31.723340000000004),
 (29.702059999999996, 33.90065),
 (29.562459999999998, 34.394090000000006),
 (30.257859999999997, 32.72253),
 (30.124840000000003, 33.22025),
 (29.78003, 34.45895),
 (30.34328, 33.28291),
 (30.068, 34.276709999999994),
 (30.355520000000002, 34.0936),
 (30.71756, 29.908490000000004),
 (30.938670000000002, 29.96309),
 (31.27723, 30.08935),
 (30.82132, 30.4675),
 (27.8226, 34.14966),
 (27.963390000000004, 34.36475),
 (28.51212, 33.347),
 (28.405409999999996, 33.54278),
 (28.471940000000004, 34.07761),
 (28.59474, 34.53156),
 (29.115190000000002, 33.466809999999995),
 (29.3339, 33.52851),
 (29.265559999999997, 33.77463),
 (29.84514, 32.665409999999994),
 (29.2365, 34.715959999999995),
 (30.0127, 31.85545),
 (27.99648, 29.53257),
 (28.384729999999998, 29.87857),
 (28.268440000000002, 30.3692),
 (28.431009999999997, 30.66712),
 (29.53742, 30.93875),
 (28.6526, 30.72055),
 (29.47646, 31.186740000000004),
 (30.92132, 31.0282),
 (27.659679999999998, 29.970879999999998),
 (27.269679999999997, 32.4509),
 (28.08878, 31.10319),
 (27.51255, 33.2907),
 (27.580740000000002, 33.794290000000004),
 (28.53143, 31.21179),
 (28.40748, 31.70195),
 (28.56499, 32.00322),
 (29.13202, 31.62495),
 (28.86637, 32.59023),
 (26.544690000000003, 34.00075),
 (28.16259, 28.79733),
 (28.546120000000002, 28.10652),
 (28.886309999999998, 28.696109999999997),
 (29.716070000000002, 30.1931),
 (29.93742, 30.247059999999998),
 (28.20128, 27.52212),
 (28.717609999999997, 26.08351),
 (28.89544, 26.37385),
 (28.749979999999997, 27.11778),
 (29.43852, 25.96051),
 (29.34453, 26.45996),
 (29.09706, 27.704629999999998),
 (29.56887, 26.50357),
 (29.84072, 26.296709999999997),
 (29.38615, 28.5457),
 (30.336479999999998, 24.826999999999998),
 (30.24887, 25.33236),
 (29.818790000000003, 27.59533),
 (29.608970000000003, 28.59487),
 (29.49979, 29.093120000000003),
 (30.092940000000002, 27.39139),
 (29.93832, 28.14398),
 (30.316290000000002, 27.43835),
 (30.054190000000002, 28.69443),
 (30.8311, 25.9665),
 (30.589909999999996, 27.23312),
 (30.22185, 28.995890000000003),
 (30.166390000000003, 29.24667),
 (31.101290000000002, 25.755779999999998),
 (30.762559999999997, 27.533479999999997),
 (30.71126, 27.786440000000002),
 (31.3253, 25.79947),
 (31.523709999999998, 25.849),
 (31.289709999999996, 27.116459999999996),
 (30.94417, 29.53548),
 (28.58403, 25.54684),
 (28.4458, 26.289170000000002),
 (30.73504, 31.78258),
 (30.89081, 32.093740000000004),
 (29.77082, 33.65345),
 (30.05728, 33.46863),
 (29.65141, 34.918),
 (30.20705, 33.78046),
 (30.62882, 33.09626),
 (30.493579999999998, 33.59558),
 (30.779659999999996, 33.40979),
 (31.089000000000002, 33.80283),
 (31.074690000000004, 34.04254),
 (30.65943, 30.16023),
 (30.37968, 30.35636),
 (28.03674, 33.9578),
 (27.96606, 34.196509999999996),
 (28.620390000000004, 34.38402),
 (29.00072, 34.64884),
 (29.36089, 32.46),
 (29.94906, 32.10426),
 (30.168640000000003, 32.16366),
 (30.104090000000003, 32.412729999999996),
 (27.939709999999998, 29.77716),
 (28.1623, 29.827659999999998),
 (28.104670000000002, 30.07255),
 (28.607, 29.929909999999996),
 (29.214409999999997, 30.334190000000003),
 (28.88656, 29.734859999999998),
 (29.051090000000002, 30.03388),
 (28.933759999999996, 30.52784),
 (29.03473, 31.075609999999998),
 (29.4148, 31.434440000000002),
 (31.262359999999997, 30.58052),
 (31.448859999999996, 30.41651),
 (27.543020000000002, 30.45775),
 (27.584570000000003, 31.239440000000002),
 (27.07255, 33.17456),
 (27.554859999999998, 32.26494),
 (27.77553, 32.3212),
 (27.4961, 33.99242),
 (28.28075, 32.19101),
 (28.21635, 32.43512),
 (28.4365, 32.492779999999996),
 (28.65649, 32.55092),
 (29.06914, 31.87153),
 (28.10792, 29.04265),
 (28.49339, 28.35312),
 (28.38583, 28.845609999999997),
 (28.27546, 29.33713),
 (28.21923, 29.582520000000002),
 (28.49822, 29.38693),
 (28.7767, 29.19039),
 (29.4359, 30.387829999999997),
 (29.65723, 30.44193),
 (29.697090000000003, 31.243000000000002),
 (28.150270000000003, 27.768040000000003),
 (28.85412, 25.33878),
 (28.821859999999997, 27.90608),
 (29.61788, 24.95901),
 (28.9931, 28.20086),
 (29.799159999999997, 25.250239999999998),
 (29.16318, 28.49695),
 (30.111420000000003, 24.78704),
 (30.024079999999998, 25.29113),
 (29.933840000000004, 25.79436),
 (29.69564, 27.048509999999997),
 (30.15835, 25.83685),
 (29.869459999999997, 27.344829999999998),
 (30.561420000000002, 24.86732),
 (30.28903, 26.38454),
 (30.04212, 27.6425),
 (30.698059999999998, 25.41589),
 (30.2136, 27.94155),
 (30.27658, 28.74485),
 (29.99573, 29.99738),
 (31.14675, 25.50086),
 (30.3883, 29.29872),
 (31.135509999999996, 26.81935),
 (31.086240000000004, 27.0737),
 (30.9855, 27.58165),
 (30.7753, 28.59443),
 (31.39119, 26.61058),
 (30.77498, 29.65645),
 (28.628690000000002, 25.29899),
 (29.972890000000003, 32.90996),
 (29.98902, 33.71669),
 (30.561559999999997, 33.346090000000004),
 (30.64258, 33.90959),
 (30.4963, 29.85435),
 (30.15863, 30.301479999999998),
 (28.11335, 34.407140000000005),
 (29.35592, 32.82209),
 (28.978209999999997, 33.957679999999996),
 (29.659329999999997, 32.68614),
 (29.54332, 32.812909999999995),
 (29.46851, 33.035340000000005),
 (29.056359999999998, 34.51113),
 (29.753909999999998, 32.84888),
 (29.6203, 33.34375),
 (29.41465, 34.083729999999996),
 (29.88685, 32.34675),
 (30.38805, 32.22355),
 (27.88225, 30.02151),
 (28.04635, 30.317190000000004),
 (27.98733, 30.56157),
 (29.37653, 30.63581),
 (31.45076, 31.42509),
 (31.38822, 31.935670000000002),
 (28.664270000000002, 29.683659999999996),
 (28.973440000000004, 31.3222),
 (29.31646, 30.88352),
 (31.017529999999997, 31.59057),
 (31.29908, 30.355990000000002),
 (31.20223, 30.83349),
 (27.92762, 30.805690000000002),
 (27.74434, 31.536509999999996),
 (27.579320000000003, 33.04874),
 (27.73185, 33.348659999999995),
 (27.6755, 33.5181),
 (28.4698, 31.457009999999997),
 (28.08547, 32.9225),
 (28.019009999999998, 33.16576),
 (28.75252, 31.26677),
 (28.6282, 31.75801),
 (28.50109, 32.24814),
 (28.190959999999997, 33.16442),
 (28.84875, 31.814529999999998),
 (27.36285, 31.186159999999997),
 (27.30142, 31.42845),
 (26.7854, 33.35738),
 (28.26983, 28.305970000000002),
 (28.43996, 28.59948),
 (29.60977, 29.642259999999997),
 (27.99302, 28.504440000000002),
 (28.9425, 26.12544),
 (28.70007, 27.365309999999997),
 (29.3046, 25.41938),
 (29.16726, 26.16771),
 (29.045440000000003, 27.952859999999998),
 (29.61637, 26.25335),
 (29.471729999999997, 27.00333),
 (29.27729, 29.042790000000004),
 (30.01715, 26.591890000000003),
 (29.767409999999998, 27.845579999999998),
 (29.71531, 28.09559),
 (29.554740000000002, 28.84412),
 (30.47353, 25.37395),
 (30.336240000000004, 26.13224),
 (29.990579999999998, 27.893359999999998),
 (29.83165, 28.644440000000003),
 (29.77725, 29.3932),
 (29.66631, 29.195059999999998),
 (29.944329999999997, 29.44497),
 (29.888340000000003, 24.94898),
 (31.010920000000002, 25.2037),
 (30.967059999999996, 25.4582),
 (30.92247, 26.7272),
 (30.688570000000002, 27.48572),
 (30.53949, 29.74742),
 (30.05333, 26.519109999999998),
 (30.9605, 27.28026),
 (30.81314, 26.564740000000004),
 (31.18406, 29.099220000000003),
 (30.66586, 26.34993),
 (31.433040000000002, 31.16432),
 (30.419729999999998, 33.1581),
 (29.906229999999997, 33.40593),
 (29.83888, 34.81528),
 (29.464909999999996, 34.211859999999994),
 (29.85039, 34.70572),
 (29.70898, 34.02875),
 (30.76124, 32.59564),
 (30.143159999999998, 34.83812),
 (31.080040000000004, 32.79599),
 (30.929190000000002, 33.72466),
 (30.21712, 30.051209999999998),
 (30.880359999999996, 30.21544),
 (27.88669, 33.9979),
 (28.2533, 34.01585),
 (28.67827, 33.34722),
 (28.60949, 33.58944),
 (28.8963, 33.405609999999996),
 (28.828359999999996, 33.65067),
 (29.047040000000003, 33.7124),
 (29.40155, 33.28208),
 (29.19652, 34.02044),
 (27.82948, 29.238740000000004),
 (31.4118, 31.72375),
 (29.1087, 29.78649),
 (29.15522, 30.5816),
 (29.1942, 31.378090000000004),
 (30.639909999999997, 31.2219),
 (30.95453, 31.842309999999998),
 (31.52435, 31.197709999999997),
 (31.44057, 30.63715),
 (31.386029999999998, 30.896490000000004),
 (31.5843, 31.00364),
 (27.60169, 30.214440000000003),
 (27.48365, 30.7008),
 (27.645490000000002, 30.996370000000002),
 (27.20465, 32.69239),
 (27.86722, 31.049559999999996),
 (27.49033, 32.50721),
 (27.35922, 32.99094),
 (27.9029, 31.834809999999997),
 (27.83956, 32.078140000000005),
 (27.71081, 32.563990000000004),
 (27.43838, 33.52156),
 (28.37095, 30.912329999999997),
 (28.060240000000004, 32.13434),
 (28.583440000000003, 32.77701),
 (28.755570000000002, 32.76566),
 (27.176509999999997, 31.91227),
 (27.048859999999998, 32.39504),
 (26.717840000000002, 33.59729),
 (26.64723, 33.83127),
 (28.37428, 27.813670000000002),
 (28.769679999999997, 28.15349),
 (28.44182, 29.63288),
 (28.94329, 29.487790000000004),
 (29.758229999999998, 30.99444),
 (28.76383, 25.83548),
 (28.52566, 27.0735),
 (29.16713, 24.88018),
 (28.847659999999998, 26.62205),
 (29.39188, 26.21035),
 (29.24768, 26.95852),
 (29.886229999999998, 24.7474),
 (29.843059999999998, 24.998929999999998),
 (29.422079999999998, 27.25286),
 (29.216379999999997, 28.248620000000003),
 (29.33207, 28.79437),
 (30.064940000000004, 26.34044),
 (30.241090000000003, 26.636609999999997),
 (29.83162, 29.69462),
 (30.78432, 26.220309999999998),
 (30.6396, 26.980290000000004),
 (30.436490000000003, 27.990140000000004),
 (31.008159999999997, 26.264909999999997),
 (30.91211, 26.77308),
 (30.60649, 28.291590000000003),
 (30.443920000000002, 29.047340000000002),
 (30.33195, 29.54983),
 (31.503320000000002, 24.77579),
 (31.459570000000003, 25.03146),
 (31.27895, 26.0548),
 (30.934040000000003, 27.835240000000002),
 (30.610059999999997, 29.35121),
 (30.55354, 29.60292),
 (31.51373, 25.61898),
 (31.345240000000004, 26.86481),
 (31.144029999999997, 27.62179),
 (30.875770000000003, 28.85202),
 (30.7011, 30.97073),
 (29.92616, 34.77165),
 (30.695390000000003, 32.846109999999996),
 (30.285429999999998, 34.34211),
 (30.214640000000003, 34.59028),
 (31.226290000000002, 33.10715),
 (30.60057, 30.411690000000004),
 (31.10114, 30.271109999999997),
 (28.13604, 33.75116),
 (28.183690000000002, 34.25897),
 (28.75972, 33.89543),
 (29.182640000000003, 33.22092),
 (29.687459999999998, 33.096470000000004),
 (29.55245, 33.590720000000005),
 (29.34471, 34.32975),
 (29.669970000000003, 32.26934),
 (30.04017, 32.663270000000004),
 (27.8241, 30.2656),
 (27.76525, 30.50944),
 (28.54903, 30.17591)]

In [57]:
lat.shape

(655,)

In [58]:
test = data[["LATITUDE","LONGITUDE","E0","ES0","ET0"]]

In [59]:
l = []
i = 0
for i in range(0,test.shape[0],5479) :
    l.append(test.iloc[i,:])

In [60]:
test2 = test.iloc[0:test.shape[0]:5479,:].reset_index(drop=True)

In [61]:
test2

     LATITUDE  LONGITUDE    E0   ES0   ET0
0    31.53312   31.90678  2.39  1.95  3.02
1    31.53312   31.90678  1.82  1.51  1.78
2    28.82912   29.98168  1.99  1.61  2.03
3    28.87405   30.77442  2.04  1.69  2.18
4    31.07981   31.33852  2.18  1.94  2.21
..        ...        ...   ...   ...   ...
801  30.04017   32.66327  8.54  7.68  7.36
802  27.82410   30.26560  7.46  6.57  6.44
803  27.76525   30.50944  7.36  6.48  6.27
804  28.54903   30.17591  8.50  7.54  7.38
805  28.54903   30.17591  8.24  7.27  8.00

[806 rows x 5 columns]

In [62]:
from shapely.geometry import Point
from shapely.geometry.polygon import Polygon

point = Point(3.1,3)
polygon = Polygon([(0, 5), (3, 5), (3, 0), (4, 3), (0, 5)])
print(polygon.contains(point))

True

In [63]:
polygon = Polygon([(29.600635,24.230134), (29.600635,32.007121), (32.578295,32.007121) , (32.578295,24.230134)])
cropland = []
for i in locations :
    point = Point(i[1],i[0])
    if polygon.contains(point) :
        cropland.append(i)

In [64]:
len(cropland)

219

In [65]:
polygon1 = Polygon([(29.997256,30.553554), (29.265108,30.804533), (30.054116,31.286967), (31.054001,31.780456), (30.996771,31.576948), (31.467683,31.360989), (31.907469,31.483860), (32.541322,31.02579), (31.855108,30.330934), (31.247167,29.956275), (29.997256,30.553554)])

In [66]:
polygon2 = Polygon([(31.147909,29.937105), (31.217487, 29.562958), (30.980337, 29.234050), (31.215167,29.207600), (31.302881,29.738412), (31.247167,29.956275), (31.147909,29.937105)])

In [67]:
polygon3 = Polygon([(30.379625,29.454016), (31.061737,29.603812), (30.980337,29.234050), (30.615178,29.099102), (30.379625,29.454016)])

In [68]:
polygon4 = Polygon([(25.262478,29.272652), (25.934006,29.368544), (26.126448,29.173870), (25.478019,29.035640), (25.262478,29.272652)])

In [69]:
polygon5 = Polygon([(30.980337,29.234050), (30.537126,28.356916), (30.741161,27.394532), (32.088735,25.971885), (32.717340,24.380433) , (33.518158,24.360838) , (32.78644,26.148146), (31.977125,26.343748), (31.338106,27.211401), (31.215167,29.207600), (30.980337,29.234050)])

In [70]:
polygon6 = Polygon([(28.808434,28.445749), (29.019079, 28.487244), (29.089343,28.296728), (28.843950,28.291394), (28.808434,28.445749)])

In [71]:
polygon7 = Polygon([(27.425275,27.208594), (27.759150,26.451762), (27.758150,26.451762), (27.425275,26.580729), (27.425275,27.208594)])

In [72]:
polygon8 = Polygon([(28.730365,25.74374), (30.723688,25.73609), (30.706538,24.608874), (28.730365,25.74374)])

In [73]:
inside = []
for i in locations :
    point = Point(i[1],i[0])
    if polygon1.contains(point) or polygon2.contains(point) or polygon3.contains(point) or polygon4.contains(point) or polygon5.contains(point) or polygon6.contains(point) or polygon7.contains(point) or polygon8.contains(point) :
        inside.append(i)

In [74]:
len(inside)

84

In [75]:
inside

[(31.07981, 31.338520000000003),
 (31.361290000000004, 31.144609999999997),
 (30.98198, 30.77614),
 (31.141379999999998, 31.086159999999996),
 (30.26019, 30.85722),
 (30.19939, 31.10722),
 (30.812240000000003, 29.41587),
 (30.97865, 29.724890000000002),
 (30.761570000000003, 30.71926),
 (30.2956, 31.664590000000004),
 (31.299529999999997, 31.39757),
 (28.592370000000003, 30.9663),
 (28.81363, 31.02073),
 (30.85994, 31.279970000000002),
 (31.07909, 32.1623),
 (27.4236, 30.943609999999996),
 (27.80612, 31.29317),
 (28.149359999999998, 30.858790000000003),
 (30.45208, 31.9736),
 (30.67152, 32.03342),
 (31.15075, 30.025309999999998),
 (31.236859999999997, 31.6497),
 (31.15617, 31.89647),
 (29.255679999999998, 31.130940000000002),
 (30.57801, 31.47277),
 (30.79785, 31.53142),
 (31.04192, 30.523770000000003),
 (30.320290000000004, 30.60693),
 (29.21375, 25.91848),
 (31.12585, 29.8359),
 (30.541009999999996, 30.66286),
 (30.48072, 30.91374),
 (28.20925, 30.61412),
 (31.036340000000003, 32.40337),
 (27.70572, 30.75303),
 (28.310190000000002, 31.15727),
 (30.13787, 31.35693),
 (29.259529999999998, 25.66904),
 (30.35802, 31.414609999999996),
 (30.5154, 31.723340000000004),
 (30.71756, 29.908490000000004),
 (30.938670000000002, 29.96309),
 (31.27723, 30.08935),
 (30.82132, 30.4675),
 (28.431009999999997, 30.66712),
 (29.53742, 30.93875),
 (28.6526, 30.72055),
 (29.47646, 31.186740000000004),
 (30.92132, 31.0282),
 (28.08878, 31.10319),
 (28.53143, 31.21179),
 (30.94417, 29.53548),
 (30.73504, 31.78258),
 (30.89081, 32.093740000000004),
 (30.65943, 30.16023),
 (29.03473, 31.075609999999998),
 (31.262359999999997, 30.58052),
 (31.448859999999996, 30.41651),
 (27.584570000000003, 31.239440000000002),
 (28.38583, 28.845609999999997),
 (29.697090000000003, 31.243000000000002),
 (30.77498, 29.65645),
 (29.37653, 30.63581),
 (31.38822, 31.935670000000002),
 (29.31646, 30.88352),
 (31.017529999999997, 31.59057),
 (31.29908, 30.355990000000002),
 (31.20223, 30.83349),
 (27.92762, 30.805690000000002),
 (27.36285, 31.186159999999997),
 (31.433040000000002, 31.16432),
 (30.880359999999996, 30.21544),
 (31.4118, 31.72375),
 (29.15522, 30.5816),
 (30.639909999999997, 31.2219),
 (30.95453, 31.842309999999998),
 (31.44057, 30.63715),
 (31.386029999999998, 30.896490000000004),
 (27.645490000000002, 30.996370000000002),
 (27.86722, 31.049559999999996),
 (28.37095, 30.912329999999997),
 (30.7011, 30.97073),
 (30.60057, 30.411690000000004),
 (31.10114, 30.271109999999997)]

In [76]:
data2 = pd.read_csv("egypt1.csv")

In [77]:
data2 = data2.transpose()

In [78]:
data2.head()

,0,1,2,3,4,5,6,7,8
Element,Arable land (000 Ha),Rice area (000 Ha),Paddy yield (t/Ha),Paddy Production (000 t),Milled production (000 t),Rice imports (000 t),Rice exports (000 t),Total rice consumption (000 t),Fertilizer usage (NPK) (000 t)
1961,"2,499.00",226,5.05,"1,142.00",761.71,NaN,254.1,777.2,96.95
1962,"2,433.00",349,5.84,"2,038.00","1,359.35",NaN,143.5,827.66,98.22
1963,"2,413.00",403,5.51,"2,219.00","1,480.07",0,380.3,873.61,114.43
1964,"2,422.00",404,5.04,"2,036.00","1,358.01",0,526.7,928.72,125.79

In [79]:
data2.columns = data2.iloc[0,:]

In [80]:
data2 = data2.drop(data2.index[0])

In [81]:
data2

Element,Arable land (000 Ha),Rice area (000 Ha),Paddy yield (t/Ha),Paddy Production (000 t),Milled production (000 t),Rice imports (000 t),Rice exports (000 t),Total rice consumption (000 t),Fertilizer usage (NPK) (000 t)
1961,"2,499.00",226,5.05,"1,142.00",761.71,NaN,254.1,777.2,96.95
1962,"2,433.00",349,5.84,"2,038.00","1,359.35",NaN,143.5,827.66,98.22
1963,"2,413.00",403,5.51,"2,219.00","1,480.07",0,380.3,873.61,114.43
1964,"2,422.00",404,5.04,"2,036.00","1,358.01",0,526.7,928.72,125.79
1965,"2,582.00",356,5.03,"1,789.00","1,193.26",0,330.4,944.58,130.76
1966,"2,683.00",355,4.73,"1,678.00","1,119.23",0.01,346.69,961.79,107.29
1967,"2,694.00",452,5.04,"2,278.00","1,519.43",NaN,434.93,"1,013.96",104.21
1968,"2,687.00",507,5.11,"2,591.00","1,728.20",0.01,569.92,"1,067.76",119.49
1969,"2,725.00",502,5.1,"2,561.00","1,708.19",0.01,772.23,"1,093.38",127.66
1970,"2,725.00",480,5.42,"2,604.00","1,736.87",0,654.46,"1,129.63",136.84
1971,"2,735.00",477.63,5.3,"2,533.69","1,689.97",NaN,514.6,"1,175.09",136.16
1972,"2,725.00",481.41,5.21,"2,507.00","1,672.17",0.02,456.44,"1,213.95",153.65
1973,"2,723.00",418.82,5.43,"2,275.00","1,517.42",NaN,297.8,"1,227.45",148.54
1974,"2,707.00",442.34,5.07,"2,241.69","1,495.21",NaN,136.26,"1,265.16",158.33
1975,"2,691.00",442.21,5.48,"2,423.45","1,616.44",NaN,104.31,"1,316.06",186.25
1976,"2,596.00",453.03,5.08,"2,300.03","1,534.12",NaN,211.04,"1,328.63",191.45
1977,"2,499.00",436.65,5.2,"2,272.31","1,515.63",NaN,223,"1,386.13",217.39
1978,"2,395.00",434.97,5.4,"2,351.00","1,568.12",NaN,145.14,"1,417.05",242.66
1979,"2,304.00",438.89,5.72,"2,511.00","1,674.84",NaN,94.88,"1,451.80",262.24
1980,"2,286.00",408.37,5.83,"2,382.10","1,588.86",NaN,98.07,"1,469.02",290.24
1981,"2,307.00",401.68,5.57,"2,236.36","1,491.65",NaN,93.02,"1,474.11",306.85
1982,"2,305.00",430.76,5.67,"2,440.51","1,627.82",0.02,22.91,"1,504.09",343.04
1983,"2,264.74",423,5.77,"2,442.00","1,628.81",NaN,19,"1,586.77",347.55
1984,"2,275.26",413.71,5.41,"2,236.44","1,491.70",0.1,65.89,"1,598.01",349.85
1985,"2,305.00",388.6,5.95,"2,311.30","1,541.64",0.02,14.77,"1,589.93",374.62
1986,"2,318.00",423.4,5.77,"2,445.00","1,630.82",7,36.04,"1,585.64",435.38
1987,"2,288.00",412.94,5.83,"2,406.00","1,604.80",22.32,99.97,"1,612.52",441.04
1988,"2,310.00",351.6,6.06,"2,132.00","1,422.04",22.1,71.35,"1,466.59",433.46
1989,"2,296.00",413.27,6.48,"2,679.00","1,786.89",3.39,32.8,"1,797.26",409.5
1990,"2,284.00",435.91,7.27,"3,167.42","2,112.67",2.44,75.34,"2,061.42",419.86
1991,"2,267.00",462.46,7.46,"3,447.81","2,299.69",3.8,150.95,"2,221.69",424.97
1992,"2,615.28",511,7.65,"3,909.71","2,607.77",0.18,187.47,"2,373.68",335.51
1993,"2,847.00",539.07,7.72,"4,160.76","2,775.23",1.33,144.12,"2,559.37",347.08
1994,"2,846.00",579.18,7.91,"4,583.01","3,056.87",0.98,245.88,"2,763.84",296.29
1995,"2,817.00",588.54,8.14,"4,788.10","3,193.66",4.73,156.78,"2,969.95",399.86
1996,"2,710.46",590.45,8.29,"4,895.39","3,265.22",0.36,327.83,"3,034.32",427.05
1997,"2,778.92",651.21,8.42,"5,480.01","3,655.17",0.69,202.59,"3,052.37",388.19
1998,"2,793.62",517.83,8.64,"4,474.11","2,984.23",0.7,428.92,"2,984.92",419.22
1999,"2,994.00",655.21,8.88,"5,816.96","3,879.91",6.04,306.97,"3,150.76",393.95
2000,"2,801.00",659.22,9.1,"6,000.49","4,002.33",1.21,392.99,"3,231.80",449.74
2001,"2,861.00",563.02,9.28,"5,226.70","3,486.21",98.52,656.19,"3,177.22",457.31
2002,"2,936.00",650.29,9.39,"6,105.46","4,072.34",1.34,464.38,"3,632.09",432.53
2003,"2,906.00",633.57,9.75,"6,176.27","4,119.57",1.92,585.74,"3,574.85",627.75
2004,"2,965.00",645.67,9.84,"6,352.37","4,237.03",2.93,836.48,"3,489.07",557.6
2005,"2,563.00",613.3,9.99,"6,125.30","4,085.58",4.42,"1,111.50","3,219.02",672.88
2006,"2,605.00",670.47,10.07,"6,755.00","4,505.58",105.67,982.76,"3,484.97",492.12
2007,"2,564.00",704.05,9.77,"6,876.83","4,586.85",117.86,"1,223.32","3,606.61",521.79
2008,"2,642.00",745.09,9.73,"7,253.37","4,838.00",42.67,306.83,"3,699.04",696.59
2009,"2,884.00",575.47,9.59,"5,520.48","3,682.16",15.65,648.7,"3,520.03",502.83
2010,"2,873.00",459.52,9.42,"4,329.50","2,887.78",17.55,599.74,"3,252.56",605.06
2011,"2,808.00",593.18,9.57,"5,675.03","3,785.24",93.72,39.97,"3,665.40",600.47
2012,"2,829.00",620.28,9.53,"5,911.09",NaN,291.25,146.87,NaN,569.54
2013,"2,738.00",597.1,9.59,"5,724.11",NaN,20.36,335.77,NaN,636.39
2014,NaN,629.6,9.53,"6,000.00",NaN,NaN,NaN,NaN,NaN

In [82]:
crop_cal = pd.read_excel("export.xls")

In [83]:
crop_cal

,Country,Agro-ecological zones,Administrative areas,Agricultural practices,Crop,Scientific name,Botanical family,Other names,Additional Information,Planting period - onset,Planting period - end,Sowing / Planting rate,Sowing/Planting rate unit,Preferred sowing/planting period,Length of the cropping cycle,Harvesting period - onset,Harvesting period - end,Comments
0,Egypt,Delta region,"Cairo, Kalubia, Menofia, Sharqiea, Daqahlia, G...",Clay to salty clay soils (Nile transmitted) fu...,Rice,Oryza sativa L.,Poaceae,NaN,Direct sowing,10/05,31/05,125-150,kg/ha,null-null,110-140 days,01/09,31/10,NaN
1,Egypt,Delta region,"Cairo, Kalubia, Menofia, Sharqiea, Daqahlia, G...",Clay to salty clay soils (Nile transmitted) fu...,Rice,Oryza sativa L.,Poaceae,NaN,Traditional nursery,25/04,15/05,70-100,kg/ha,null-null,120-160 days,01/09,31/10,NaN
2,Egypt,Middle Egypt Region,"Giza, Fayoum. Beni Sweaf and El-Minya",Clay to salty clay soils (Nile transmitted) fu...,Rice,Oryza sativa L.,Poaceae,NaN,NaN,20/04,10/05,90-120,kg/ha,null-null,120-150 days,01/08,30/09,NaN